# Generated by Django 5.1.3 on 2024-12-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_alter_sensorreading_adapter_connection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorreading',
            old_name='sensor_calibration_date',
            new_name='calibration_date',
        ),
        migrations.RenameField(
            model_name='sensorreading',
            old_name='test_referance',
            new_name='sample_referance_monitor',
        ),
        migrations.RenameField(
            model_name='sensorreading',
            old_name='sensor_sr_number',
            new_name='serial_number',
        ),
        migrations.RenameField(
            model_name='sensorreading',
            old_name='use_date',
            new_name='update_date',
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='sample_referance_config',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
