# Generated by Django 5.1.3 on 2024-12-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0005_rename_sample_referance_config_sensorreading_sample_reference_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
